apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: syfosmregister
  namespace: default
  labels:
    team: "teamsykefravr"
spec:
  name: "syfosmregister"
  image: "repo.adeo.no:5443/syfo/syfosmregister:@@VERSION@@"
  replicas:
    min: 1
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 5
    timeout: 1
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /is_ready
    initialDelay: 5
    timeout: 1
    periodSeconds: 10
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 200m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 128Mi
  vault:
    enabled: true
  ingresses:
    - "https://syfosmregister.nais.preprod.local"
    - "https://syfosmregister.nais.adeo.no"
  webproxy: true
  env:
  - name: KAFKA_BOOTSTRAP_SERVERS_URL
    value: {{KAFKA_BOOTSTRAP_SERVERS_URL}}
  - name: SYFOSMREGISTER_DB_URL
    value: {{SYFOSMREGISTER_DB_URL}}
  - name: MOUNT_PATH_VAULT
    value: {{MOUNT_PATH_VAULT}}
  - name: CLUSTER
    value: {{CLUSTER}}
