openapi: 3.0.1

info:
  title: Syfosmregister API
  description: API for sykmeldinger.
  version: 1.0.0
servers:
  - url: 'https://api.example.com'
paths:
  /api/v1/sykmeldinger:
    get:
      parameters:
        - $ref: '#/components/parameters/fnrQueryParam'
        - $ref: '#/components/parameters/sykmeldingTypeQueryParam'
      summary: Returns a list of sykmeldinger for logged in user.
      description: Optional extended description in Markdown.
      responses:
        '200':
          $ref: '#/components/responses/SykmeldingListResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

components:
  responses:
    SykmeldingListResponse:
      description: "Returns list of sykmeldinger"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/sykmeldingList'
  parameters:
    fnrQueryParam:
      name: fnr
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/Personnr'
    sykmeldingTypeQueryParam:
      in: query
      name: type
      required: false
      schema:
        type: string
        enum: [arbeidsgiver, saksbehandler]
  schemas:
    Date:
      type: string
      format: date
    Timestamp:
      type: string
      format: 'date-time'
    Personnr:
      type: string
      minimum: 11
      maximum: 11
    StatusEvent:
      type: string
      enum: [APEN, AVBRUTT, UTGATT, SENDT, BEKREFTET]
    SykmeldingStatus:
      type: object
      required:
        - timestamp
        - statusEvent
      properties:
        timestamp:
          $ref: '#/components/schemas/Timestamp'
        statusEvent:
          $ref: '#/components/schemas/StatusEvent'
    RegelStatus:
      type: object
      properties:
        status:
          type: string
          enum: [OK, MANUAL_PROCESSING, INVALID]
    RegelInfo:
      type: object
      properties:
        messageForSender:
          type: string
        messageForUser:
          type: string
        ruleName:
          type: string
        ruleStatus:
          $ref: '#/components/schemas/RegelStatus'
    Behandlingsutfall:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/RegelStatus'
        ruleHits:
          type: array
          items:
            $ref: '#/components/schemas/RegelInfo'
    Arbeidsgiver:
      type: object
      required:
        - navn
      properties:
        navn:
          type: string
        stillingsprosent:
          type: integer
          format: int32
          minimum: 0
          maximum: 100
    Gradert:
      type: object
      properties:
        grad:
          type: integer
          minimum: 0
          maximum: 100
        reisetilskudd:
          type: boolean
    Periodetype:
      type: string
      enum: [ AKTIVITET_IKKE_MULIG, AVVENTENDE, BEHANDLINGSDAGER, GRADERT, REISETILSKUDD]
    Sykmeldingsperiode:
      type: object
      properties:
        fom:
          $ref: '#/components/schemas/Date'
        tom:
          $ref: '#/components/schemas/Date'
        gradert:
          $ref: '#/components/schemas/Gradert'
        behandlingsdager:
          type: integer
        innspillTilArbeidsgiver:
          type: string
        type:
          type: string
    Diagnose:
      type: object
      properties:
        diagnosekode:
          type: string
        diagnosesystem:
          type: string
        diagnosetekst:
          type: string
    MedisinskVurdering:
      description: Medisinsk vurdering er bare tilgjengelig for brukere med tilgang til det. Den er ikke med for arbeidsgivere eller der sykmeldingen skal skjermes for pasienten
      type: object
      required:
        - biDiagnoser
      properties:
        hovedDiagnose:
          $ref: '#/components/schemas/Diagnose'
        biDiagnoser:
          type: array
          items:
            $ref: '#/components/schemas/Diagnose'
    sykmeldingList:
      type: array
      items:
        $ref: '#/components/schemas/Sykmelding'
    Sykmelding:
      type: object
      required:
        - id
        - mottattTidspunkt
        - sykmeldingStatus
        - behandlingsutfall
        - sykmeldingsperioder
      properties:
        id:
          $ref: '#/components/schemas/Personnr'
        mottattTidspunkt:
          $ref: '#/components/schemas/Timestamp'
        sykmeldingStatus:
          $ref: '#/components/schemas/SykmeldingStatus'
        behandlingsutfall:
          $ref: '#/components/schemas/Behandlingsutfall'
        legekontorOrgnummer:
          type: string
        legeNavn:
          type: string
        arbeidsgiver:
          $ref: '#/components/schemas/Arbeidsgiver'
        sykmeldingsperioder:
          type: array
          items:
            $ref: '#/components/schemas/Sykmeldingsperiode'
        medisinskVurdering:
          $ref: '#/components/schemas/MedisinskVurdering'









