openapi: 3.0.1

info:
  title: Syfosmregister API
  description: API for sykmeldinger.
  version: 1.0.0
servers:
  - url: 'https://syfosmregister.nais.preprod.local'
paths:
  /api/v1/sykmeldinger:
    get:
      operationId: getSykmeldingerForBruker
      security:
        - bearerAuth: []
      tags:
        - Sykmelding
      parameters:
        - $ref: '#/components/parameters/fnrQueryParam'
      summary: Returnerer sykmeldinger for oppgitt fnr
      responses:
        200:
          $ref: '#/components/responses/SykmeldingListResponse'
        401:
          description: Unauthorized
        403:
          description: Forbidden
  /api/v1/sykmeldinger/{sykmeldingId}/bekreft:
    post:
      operationId: bekreftAvvistSykmelding
      tags:
        - Sykmelding
      summary: Bekreft avviste sykmeldinger
      parameters:
        - $ref: '#/components/parameters/sykmeldingId'
      responses:
        200:
          description: Ok
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /sykmeldinger/{sykmeldingId}/status:
    post:
      operationId: addStatus
      tags:
        - Sykmelding status
      summary: Api for å lagre status for sykmelding
      parameters:
        - $ref: '#/components/parameters/sykmeldingId'
      responses:
        201:
          description: Created
        401:
          description: Unauthorized
        403:
          description: Forbidden
      requestBody:
        $ref: '#/components/requestBodies/StatusRequest'
  /sykmeldinger/{sykmeldingId}/bekreft:
    post:
      operationId: bekreftSykmelding
      tags:
        - Sykmelding status
      summary: API for bekrefting av sykmeldinger
      parameters:
        - $ref: '#/components/parameters/sykmeldingId'
      responses:
        201:
          description: Created
        401:
          description: Unauthorized
        403:
          description: Forbidden
      requestBody:
        $ref: '#/components/requestBodies/SykmeldingBekreftEvent'
  /sykmeldinger/{sykmeldingId}/send:
    post:
      operationId: sendSykmelding
      tags:
        - Sykmelding status
      summary: API for sending av sykmeldinger
      parameters:
        - $ref: '#/components/parameters/sykmeldingId'
      responses:
        201:
          description: Created
        401:
          description: Unauthorized
        403:
          description: Forbidden
      requestBody:
        $ref: '#/components/requestBodies/SykmeldingSendEvent'


  /api/v1/internal/sykmeldinger:
    get:
      operationId: getSykmeldinger
      tags:
        - Sykmelding
        - Internal
      parameters:
        - $ref: '#/components/parameters/fnrQueryParam'
      summary: API for saksbehandlere og interne. Returnerer liste med sykmledinger basert på fnr
      responses:
        200:
          $ref: '#/components/responses/InternalSykmeldingerResponse'
        401:
          description: Unauthorized
        403:
          description: Forbidden


components:
  requestBodies:
    StatusRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SykmeldingStatusEvent'
    SykmeldingBekreftEvent:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SykmeldingBekreftEvent'
    SykmeldingSendEvent:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SykmeldingSendEvent'
  responses:
    InternalSykmeldingerResponse:
      description: "Response for internal sykmeldinger for saksbehandlere"
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/InternalSykmelding'
    SykmeldingListResponse:
      description: "Returnerer liste med sykmeldinger"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/sykmeldingList'
  parameters:
    sykmeldingId:
      description: Id for sykmelding
      name: sykmeldingId
      in: path
      required: true
      schema:
        type: string
    fnrQueryParam:
      description: Fodselsnummer
      name: fnr
      in: query
      required: true
      schema:
        $ref: '#/components/schemas/Fodselsnummer'
  schemas:
    Date:
      type: string
      format: date
    Timestamp:
      type: string
      format: 'date-time'
    Fodselsnummer:
      type: string
      minLength: 11
      maxLength: 11
    StatusEvent:
      type: string
      enum: [SENDT, APEN, AVBRUTT, UTGATT, BEKREFTET]
    SykmeldingStatusEvent:
      type: object
      required:
        - timestamp
        - statusEvent
      properties:
        timestamp:
          $ref: '#/components/schemas/Timestamp'
        statusEvent:
          $ref: '#/components/schemas/StatusEvent'
    RegelStatus:
      type: object
      properties:
        status:
          type: string
          enum: [OK, MANUAL_PROCESSING, INVALID]
    RegelInfo:
      type: object
      required:
        - messageForSender
        - messageForUser
        - ruleName
      properties:
        messageForSender:
          type: string
        messageForUser:
          type: string
        ruleName:
          type: string
        ruleStatus:
          $ref: '#/components/schemas/RegelStatus'
    Behandlingsutfall:
      type: object
      required:
        - status
        - ruleHits
      properties:
        status:
          $ref: '#/components/schemas/RegelStatus'
        ruleHits:
          type: array
          items:
            $ref: '#/components/schemas/RegelInfo'
    Arbeidsgiver:
      type: object
      properties:
        navn:
          type: string
        stillingsprosent:
          type: integer
          format: int32
          minimum: 0
          maximum: 100
    Gradert:
      type: object
      properties:
        grad:
          type: integer
          minimum: 0
          maximum: 100
        reisetilskudd:
          type: boolean
    Periodetype:
      type: string
      enum: [ AKTIVITET_IKKE_MULIG, AVVENTENDE, BEHANDLINGSDAGER, GRADERT, REISETILSKUDD]
    Sykmeldingsperiode:
      type: object
      required:
        - fom
        - tom
        - type
        - reisetilskudd
      properties:
        fom:
          $ref: '#/components/schemas/Date'
        tom:
          $ref: '#/components/schemas/Date'
        gradert:
          $ref: '#/components/schemas/Gradert'
        behandlingsdager:
          type: integer
        innspillTilArbeidsgiver:
          type: string
        type:
          $ref: '#/components/schemas/Periodetype'
    AktivitetIkkeMulig:
      type: object
      properties:
        medisinskArsak:
          $ref: '#/components/schemas/MedisinskArsak'
        arbeidsrelatertArsak:
          $ref: '#/components/schemas/ArbeidsrelatertArsak'
    MedisinskArsak:
      type: object
      properties:
        beskrivelse:
          type: string
        arsak:
          type: array
          items:
            $ref: '#/components/schemas/MedisinskArsakType'
    MedisinskArsakType:
      type: string
      enum: [TILSTAND_HINDRER_AKTIVITET, AKTIVITET_FORVERRER_TILSTAND, AKTIVITET_FORHINDRER_BEDRING, ANNET]
    ArbeidsrelatertArsak:
      type: object
      properties:
        beskrivelse:
          type: string
        arsak:
          type: array
          items:
            $ref: '#/components/schemas/ArbeidsrelatertArsakType'
    ArbeidsrelatertArsakType:
      type: string
      enum: [MANGLENDE_TILRETTELEGGING, ANNET]
    Diagnose:
      type: object
      properties:
        kode:
          type: string
        system:
          type: string
        tekst:
          type: string
    MedisinskVurdering:
      description: Medisinsk vurdering er bare tilgjengelig for brukere med tilgang til det.
      type: object
      required:
        - biDiagnoser
      properties:
        hovedDiagnose:
          $ref: '#/components/schemas/Diagnose'
        biDiagnoser:
          type: array
          description: påkreved men kan være en tom liste
          items:
            $ref: '#/components/schemas/Diagnose'
    sykmeldingList:
      type: array
      items:
        $ref: '#/components/schemas/Sykmelding'
    Sykmelding:
      type: object
      required:
        - id
        - mottattTidspunkt
        - sykmeldingStatus
        - behandlingsutfall
        - sykmeldingsperioder
      properties:
        id:
          $ref: '#/components/schemas/Fodselsnummer'
        mottattTidspunkt:
          $ref: '#/components/schemas/Timestamp'
        sykmeldingStatus:
          $ref: '#/components/schemas/SykmeldingStatus'
        behandlingsutfall:
          $ref: '#/components/schemas/Behandlingsutfall'
        legekontorOrgnummer:
          type: string
        legeNavn:
          type: string
        arbeidsgiver:
          $ref: '#/components/schemas/Arbeidsgiver'
        sykmeldingsperioder:
          type: array
          items:
            $ref: '#/components/schemas/Sykmeldingsperiode'
        medisinskVurdering:
          $ref: '#/components/schemas/MedisinskVurdering'
    SvarType:
      type: string
      enum: [ARBEIDSSITUASJON, PERIODER, JA_NEI]
    SporsmalShortName:
      type: string
      enum: [ARBEIDSSITUASJON, NY_NARMESTE_LEDER, FRAVAER, PERIODE, FORSIKRING]
    SporsmalOgSvar:
      type: object
      properties:
        tekst:
          type: string
        svar:
          type: string
        svartype:
          $ref: '#/components/schemas/SvarType'
        shortName:
          $ref: '#/components/schemas/SporsmalShortName'
    SposmalOgSvarListe:
      type: array
      description: Liste med spørsmål og svar, er kun tilgjengelig om Status er SENDT eller BEKREFTET
      items:
        $ref: '#/components/schemas/SporsmalOgSvar'
    ArbeidsgiverStatus:
      type: object
      required:
        - orgnummer
        - orgNavn
      properties:
        orgnummer:
          type: string
        juridiskOrgnummer:
          type: string
        orgNavn:
          type: string
    SykmeldingBekreftEvent:
      type: object
      required:
        - timestamp
        - sporsmalOgSvarListe
      properties:
        timestamp:
          $ref: '#/components/schemas/Timestamp'
        sporsmalOgSvarListe:
          $ref: '#/components/schemas/SposmalOgSvarListe'
    SykmeldingSendEvent:
      type: object
      allOf:
        - $ref: '#/components/schemas/SykmeldingBekreftEvent'
      required:
        - arbeidsgiver
      properties:
        arbeidsgiver:
          $ref: '#/components/schemas/ArbeidsgiverStatus'
    InternalSykmelding:
      type: object
      required:
        - id
        - mottattTidspunkt
        - behandlingsutfall
        - sykmeldingsperioder
        - sykmeldingStatus
        - medisinskVurdering
        - skjermesForPasient
        - utdypendeOpplysninger
        - kontaktMedPasient
        - behandletTidspunkt
        - behandler
      properties:
        id:
          type: string
        mottattTidspunkt:
          $ref: '#/components/schemas/Timestamp'
        behandlingsutfall:
          $ref: '#/components/schemas/Behandlingsutfall'
        legekontorOrgnummer:
          type: string
        arbeidsgiver:
          $ref: '#/components/schemas/Arbeidsgiver'
        sykmeldingsperioder:
          type: array
          items:
            $ref: '#/components/schemas/InternalSykmeldingsperiode'
        sykmeldingStatus:
            $ref: '#/components/schemas/SykmeldingStatus'
        medisinskVurdering:
          $ref: '#/components/schemas/InternalMedisinskVurdering'
        skjermesForPasient:
          type: boolean
        prognose:
          $ref: '#/components/schemas/Prognose'
        utdypendeOpplysninger:
          $ref: '#/components/schemas/UtdypendeOpplysninger'
        tiltakArbeidsplassen:
          type: string
        tiltakNAV:
          type: string
        andreTiltak:
          type: string
        meldingTilNAV:
          $ref: '#/components/schemas/MeldingTilNavDTO'
        meldingTilArbeidsgiver:
          type: string
        kontaktMedPasient:
          $ref: '#/components/schemas/KontaktMedPasient'
        behandletTidspunkt:
          $ref: '#/components/schemas/Timestamp'
        behandler:
          $ref: '#/components/schemas/Behandler'
        syketilfelleStartDato:
          $ref: '#/components/schemas/Date'
        navnFastLege:
          type: string
    Prognose:
      type: object
      required:
        - arbeidsforEtterPeriode
      properties:
        arbeidsforEtterPeriode:
          type: boolean
        hensynArbeidsplassen:
          type: string
        erIArbeid:
          type: object
          properties:
            egetArbeidPaSikt:
              type: boolean
            annetArbeidPaSikt:
              type: boolean
            arbeidFOM:
              $ref: '#/components/schemas/Date'
            vurderingsdato:
              $ref: '#/components/schemas/Date'
    MeldingTilNavDTO:
      type: object
      required:
        - bistandUmiddelbart
      properties:
        bistandUmiddelbart:
          type: boolean
        beskrivBistand:
          type: string
    KontaktMedPasient:
      type: object
      properties:
        kontaktDato:
          $ref: '#/components/schemas/Date'
        begrunnelseIkkeKontakt:
          type: string
    Behandler:
      type: object
      required:
        - fornavn
        - etternavn
        - aktoerId
        - fnr
        - adresse
      properties:
        fornavn:
          type: string
        mellomnavn:
          type: string
        etternavn:
          type: string
        aktoerId:
          type: string
        fnr:
          $ref: '#/components/schemas/Fodselsnummer'
        hpr:
          type: string
        her:
          type: string
        adresse:
          $ref: '#/components/schemas/Adresse'
        tlf:
          type: string
    Adresse:
      type: object
      properties:
        gate:
          type: string
        postnummer:
          type: integer
        kommune:
          type: string
        postboks:
          type: string
        land:
          type: string
    UtdypendeOpplysninger:
      description: påkrevd, og kan være et tomt map
      type: object
      additionalProperties:
        type: object
        additionalProperties:
          type: object
          required:
            - sporsmal
            - svar
            - restriksjoner
          properties:
            sporsmal:
              type: string
            svar:
              type: string
            restriksjoner:
              type: array
              items:
                type: string
                enum: [SKJERMET_FOR_ARBEIDSGIVER, SKJERMET_FOR_PASIENT]
      example:
        6.2: {
          6.2.1: {
            svar: "Veldig syk med masse feber.",
            sporsmal: "Beskriv kort sykehistorie, symptomer og funn i dagens situasjon.",
            restriksjoner: [
              "SKJERMET_FOR_ARBEIDSGIVER"
            ]
          },
          6.2.2: {
            svar: "Kan ikke arbeide nå",
            sporsmal: "Hvordan påvirker sykdommen arbeidsevnen?",
            restriksjoner: [
              "SKJERMET_FOR_ARBEIDSGIVER"
            ]
          },
          6.2.3: {
            svar: "Avslapping",
            sporsmal: "Har behandlingen frem til nå bedret arbeidsevnen?",
            restriksjoner: [
              "SKJERMET_FOR_ARBEIDSGIVER"
            ]
          },
          6.2.4: {
            svar: "Ikke aktuelt",
            sporsmal: "Beskriv pågående og planlagt henvisning,utredning og/eller behandling.",
            restriksjoner: [
              "SKJERMET_FOR_ARBEIDSGIVER"
            ]
          }
        }
    InternalSykmeldingsperiode:
      type: object
      allOf:
        - $ref: '#/components/schemas/Sykmeldingsperiode'
      properties:
        aktivitetIkkeMulig:
          $ref: '#/components/schemas/AktivitetIkkeMulig'
    InternalMedisinskVurdering:
      type: object
      allOf:
        - $ref: '#/components/schemas/MedisinskVurdering'
      properties:
        svangerskap:
          type: boolean
        yrkesskade:
          type: boolean
        yrkesskadeDato:
          type: string
          format: date
        annenFraversArsak:
          $ref: '#/components/schemas/AnnenFraversArsak'
    AnnenFraversArsak:
      type: object
      properties:
        beskrivelse:
          type: string
        grunn:
          type: array
          items:
            $ref: '#/components/schemas/AnnenFraverGrunn'
    AnnenFraverGrunn:
      type: string
      enum: [GODKJENT_HELSEINSTITUSJON,
             BEHANDLING_FORHINDRER_ARBEID,
             ARBEIDSRETTET_TILTAK,
             MOTTAR_TILSKUDD_GRUNNET_HELSETILSTAND,
             NODVENDIG_KONTROLLUNDENRSOKELSE,
             SMITTEFARE,
             ABORT,
             UFOR_GRUNNET_BARNLOSHET,
             DONOR,
             BEHANDLING_STERILISERING]
    SykmeldingStatus:
      type: object
      allOf:
        - $ref: '#/components/schemas/SykmeldingStatusEvent'
      properties:
        arbeidsgiver:
          description: Arbeidsgiver er bare tilgjengelig om sykmeldingStatus.statusevent = SENDT
          type: object
          properties:
            orgNr:
              type: string
            juridiskOrgNr:
              type: string
            navn:
              type: string
        sporsmalOgSvarListe:
          $ref: '#/components/schemas/SposmalOgSvarListe'


  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []








